name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: "src"
        
    - name: Checkout builds
      uses: actions/checkout@v2
      with:
        ref: "builds"
        path: "builds"
        
    - name: Clean old builds
      run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true
      
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Access Secrets
      env:
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
      run: |
        cd $GITHUB_WORKSPACE/src
        echo DISCORD_URL=$DISCORD_URL > .env
        
    - name: Build Plugins
      run: |
        cd $GITHUB_WORKSPACE/src
        chmod +x gradlew
        ./gradlew make makePluginsJson
        cp */*.cs3 $GITHUB_WORKSPACE/builds
        cp plugins.json $GITHUB_WORKSPACE/builds
        
    - name: Move to builds
      run: |
        cd $GITHUB_WORKSPACE/builds
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git diff --staged --quiet || git commit -m "Build $GITHUB_SHA" || true
        
    - name: Push builds
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: builds
        directory: builds
